/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.sistema_inventarios.Visual;

import com.proyectofinal.sistema_inventarios.Config.SpringJdbcConfig;
import com.proyectofinal.sistema_inventarios.DAO.InvoiceImplementation;
import com.proyectofinal.sistema_inventarios.DAO.ProductDAOimplementation;
import com.proyectofinal.sistema_inventarios.DAO.SalesImplementation;
import com.proyectofinal.sistema_inventarios.DAO.TipoPagoImplementacion;
import com.proyectofinal.sistema_inventarios.DAO.UserDAOimplementation;
import com.proyectofinal.sistema_inventarios.repository.InvoiceRepo;
import com.proyectofinal.sistema_inventarios.repository.ProductRepo;
import com.proyectofinal.sistema_inventarios.repository.SalesRepo;
import com.proyectofinal.sistema_inventarios.repository.TipoPagoRepo;
import com.proyectofinal.sistema_inventarios.repository.UserRepo;
import com.proyectofinal.sistema_inventarios.service.Invoices;
import com.proyectofinal.sistema_inventarios.service.Product;
import com.proyectofinal.sistema_inventarios.service.TipoPago;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.util.EventListener;
import com.proyectofinal.sistema_inventarios.service.Users;
import java.util.LinkedList;

/**
 *
 * @author sebastianzumbado
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    @Autowired
    private static SpringJdbcConfig springJdbcConfig =new SpringJdbcConfig();
    private static UserRepo userRepo = new UserDAOimplementation(springJdbcConfig.postgresqlDataSource());
    private static ProductRepo productRepo = new ProductDAOimplementation(springJdbcConfig.postgresqlDataSource());
    private static SalesRepo salesRepo = new SalesImplementation(springJdbcConfig.postgresqlDataSource());
    private static TipoPagoRepo tipoPagoRepo= new TipoPagoImplementacion(springJdbcConfig.postgresqlDataSource());
    private static InvoiceRepo invoiceRepo = new InvoiceImplementation(springJdbcConfig.postgresqlDataSource());
    Users user = new Users();
    List<Product> products = new LinkedList<>();
    
    public Factura() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Factura(List<Product> products, Users user) {
        initComponents();
        setLocationRelativeTo(null);
        llenarTablaFactura(products);
        jButton2.setEnabled(false);
        this.user=user;
        this.products=products;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio Total Liinea"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Ingresar Forma de Pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TipoPago tipoPago = new TipoPago();
        JTextField numero = new JTextField();
        JTextField fechaEx = new JTextField();
        JTextField cvv = new JTextField();
        JComboBox<String> tipoTarjeta = new JComboBox<>();
        tipoTarjeta.addItem("Debito");
        tipoTarjeta.addItem("Credito");
        

        Object[] ingresoFormapago = {"* Ingrese el numero de tarjeta",numero, "* Ingrese la fecha de expiracion de la forma 'MM/YY'",fechaEx,
                "* Ingrese el codigo de seguridad de la tarjeta",cvv,"Seleccione el tipo de tarjeta", tipoTarjeta};
        boolean seguir = true;
        
        do{
            JOptionPane.showConfirmDialog(null,ingresoFormapago,"Ingrese la informacion para agregar la forma de Pago",JOptionPane.OK_OPTION);

            try{
                if(tipoPagoRepo.validarTarjeta(Integer.parseInt(numero.getText()),fechaEx.getText(), cvv.getText())==1){
                    jButton2.setEnabled(true);
                    seguir = false;
                }

            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Informacion ingresada erroneamente");
            }
        
        }while(seguir);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Invoices invoice = new Invoices();
        invoice.setUsers(user);
        invoice.setProducts(products);
        invoice.setInvoiceDate(LocalDateTime.now());
        invoiceRepo.subirFactura(invoice);
        invoiceRepo.subirDetalleFactura((LinkedList<Product>)products);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void llenarTablaFactura(List<Product> products){
        DefaultTableModel model = (DefaultTableModel) table.getModel(); 
       
        Object[] row = new Object[3];
        
        for(int i = 0; i<products.toArray().length;i++){
            row[0]=products.get(i).getName();
            row[1]=products.get(i).getQuantity();
            row[2]=products.get(i).getPrice()*products.get(i).getQuantity();
            
            model.addRow(row);
        }   
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
