/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.sistema_inventarios.Visual;
import com.proyectofinal.sistema_inventarios.Config.SpringJdbcConfig;
import com.proyectofinal.sistema_inventarios.DAO.ProductDAOimplementation;
import com.proyectofinal.sistema_inventarios.DAO.UserDAOimplementation;
import com.proyectofinal.sistema_inventarios.repository.ProductRepo;
import com.proyectofinal.sistema_inventarios.repository.UserRepo;
import com.proyectofinal.sistema_inventarios.service.Product;
import com.proyectofinal.sistema_inventarios.service.Users;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author sebastianzumbado
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    @Autowired
    private static SpringJdbcConfig springJdbcConfig =new SpringJdbcConfig();
    private static ProductRepo productRepo = new ProductDAOimplementation(springJdbcConfig.postgresqlDataSource());
    Users user =new Users();
    
    public Menu1() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public Menu1(Users user) {
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Realizar Compras", "Ingresar Productos", "Ver Facturas", "Salir" }));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        int opcion = menu.getSelectedIndex();
        switch(opcion){
            case 0:
                Productos productos = new Productos(user);
                productos.setVisible(true);
                dispose();
                break;
            case 1:
                ingresarProducto();
                break;
            case 2:
                GenerarFactura generarFactura = new GenerarFactura();
                generarFactura.setVisible(true);
                dispose();
                break;
            case 3:
                System.exit(0);
                break;
               
        }
                
    }//GEN-LAST:event_menuActionPerformed

    
     private void ingresarProducto() {
        Product product = new Product();
        JTextField nombre = new JTextField();
        JTextField cantidad = new JTextField();
        JTextField precio = new JTextField();
        JTextField descripcion = new JTextField();
        Object[] ingresoProducto = {"* Ingrese el nombre del producto",nombre, "* Ingrese la cantidad de producto",cantidad,
                "* Ingrese el precio del producto",precio,"Ingrese una breve descripcion del producto",descripcion};
        
        boolean seguir = true;
        try{
            
        do{
            JOptionPane.showConfirmDialog(null,ingresoProducto,"Ingrese la informacion para agregar un nuevo producto",JOptionPane.OK_OPTION);
            if(nombre.getText().equals("") || cantidad.getText().equals("")|| precio.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor en todos los espacios requeridos **");
               
                
            }else{
                seguir=false;
            }
        }while(seguir);

        product.setName(nombre.getText());
        product.setQuantity(Integer.parseInt(cantidad.getText()));
        product.setPrice(Double.parseDouble(precio.getText()));
        product.setDescription(descripcion.getText());
        product.setDateOfPurchase(LocalDateTime.now());
        
            productRepo.save(product);
            JOptionPane.showMessageDialog(null, "Producto ingresado Correctamente");

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al ingresar el producto");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> menu;
    // End of variables declaration//GEN-END:variables
}
